// Code generated for service
// © Student 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/stas137/ms-3/inventory/internal/model"
	"github.com/stas137/ms-3/inventory/internal/service/input"
	mock "github.com/stretchr/testify/mock"
)

// NewPartService creates a new instance of PartService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartService {
	mock := &PartService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PartService is an autogenerated mock type for the PartService type
type PartService struct {
	mock.Mock
}

type PartService_Expecter struct {
	mock *mock.Mock
}

func (_m *PartService) EXPECT() *PartService_Expecter {
	return &PartService_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type PartService
func (_mock *PartService) Get(ctx context.Context, partUUID uuid.UUID) (model.Part, error) {
	ret := _mock.Called(ctx, partUUID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Part, error)); ok {
		return returnFunc(ctx, partUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Part); ok {
		r0 = returnFunc(ctx, partUUID)
	} else {
		r0 = ret.Get(0).(model.Part)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, partUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PartService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type PartService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - partUUID uuid.UUID
func (_e *PartService_Expecter) Get(ctx interface{}, partUUID interface{}) *PartService_Get_Call {
	return &PartService_Get_Call{Call: _e.mock.On("Get", ctx, partUUID)}
}

func (_c *PartService_Get_Call) Run(run func(ctx context.Context, partUUID uuid.UUID)) *PartService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PartService_Get_Call) Return(part model.Part, err error) *PartService_Get_Call {
	_c.Call.Return(part, err)
	return _c
}

func (_c *PartService_Get_Call) RunAndReturn(run func(ctx context.Context, partUUID uuid.UUID) (model.Part, error)) *PartService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type PartService
func (_mock *PartService) List(ctx context.Context, filter input.PartFilter) ([]model.Part, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.PartFilter) ([]model.Part, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.PartFilter) []model.Part); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, input.PartFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PartService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type PartService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter input.PartFilter
func (_e *PartService_Expecter) List(ctx interface{}, filter interface{}) *PartService_List_Call {
	return &PartService_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *PartService_List_Call) Run(run func(ctx context.Context, filter input.PartFilter)) *PartService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 input.PartFilter
		if args[1] != nil {
			arg1 = args[1].(input.PartFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PartService_List_Call) Return(parts []model.Part, err error) *PartService_List_Call {
	_c.Call.Return(parts, err)
	return _c
}

func (_c *PartService_List_Call) RunAndReturn(run func(ctx context.Context, filter input.PartFilter) ([]model.Part, error)) *PartService_List_Call {
	_c.Call.Return(run)
	return _c
}
