// Code generated for service
// © Student 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/stas137/ms-3/payment/internal/service/input"
	mock "github.com/stretchr/testify/mock"
)

// NewPaymentService creates a new instance of PaymentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentService {
	mock := &PaymentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PaymentService is an autogenerated mock type for the PaymentService type
type PaymentService struct {
	mock.Mock
}

type PaymentService_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentService) EXPECT() *PaymentService_Expecter {
	return &PaymentService_Expecter{mock: &_m.Mock}
}

// Pay provides a mock function for the type PaymentService
func (_mock *PaymentService) Pay(ctx context.Context, in input.PayOrderInput) (uuid.UUID, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Pay")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.PayOrderInput) (uuid.UUID, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.PayOrderInput) uuid.UUID); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, input.PayOrderInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PaymentService_Pay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pay'
type PaymentService_Pay_Call struct {
	*mock.Call
}

// Pay is a helper method to define mock.On call
//   - ctx context.Context
//   - in input.PayOrderInput
func (_e *PaymentService_Expecter) Pay(ctx interface{}, in interface{}) *PaymentService_Pay_Call {
	return &PaymentService_Pay_Call{Call: _e.mock.On("Pay", ctx, in)}
}

func (_c *PaymentService_Pay_Call) Run(run func(ctx context.Context, in input.PayOrderInput)) *PaymentService_Pay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 input.PayOrderInput
		if args[1] != nil {
			arg1 = args[1].(input.PayOrderInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PaymentService_Pay_Call) Return(uUID uuid.UUID, err error) *PaymentService_Pay_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *PaymentService_Pay_Call) RunAndReturn(run func(ctx context.Context, in input.PayOrderInput) (uuid.UUID, error)) *PaymentService_Pay_Call {
	_c.Call.Return(run)
	return _c
}
