// Code generated for service
// © 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/stas137/ms-3/inventory/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewPartRepository creates a new instance of PartRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartRepository {
	mock := &PartRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PartRepository is an autogenerated mock type for the PartRepository type
type PartRepository struct {
	mock.Mock
}

type PartRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PartRepository) EXPECT() *PartRepository_Expecter {
	return &PartRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type PartRepository
func (_mock *PartRepository) Get(ctx context.Context, partUUID uuid.UUID) (model.Part, error) {
	ret := _mock.Called(ctx, partUUID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Part, error)); ok {
		return returnFunc(ctx, partUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Part); ok {
		r0 = returnFunc(ctx, partUUID)
	} else {
		r0 = ret.Get(0).(model.Part)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, partUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PartRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type PartRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - partUUID uuid.UUID
func (_e *PartRepository_Expecter) Get(ctx interface{}, partUUID interface{}) *PartRepository_Get_Call {
	return &PartRepository_Get_Call{Call: _e.mock.On("Get", ctx, partUUID)}
}

func (_c *PartRepository_Get_Call) Run(run func(ctx context.Context, partUUID uuid.UUID)) *PartRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PartRepository_Get_Call) Return(part model.Part, err error) *PartRepository_Get_Call {
	_c.Call.Return(part, err)
	return _c
}

func (_c *PartRepository_Get_Call) RunAndReturn(run func(ctx context.Context, partUUID uuid.UUID) (model.Part, error)) *PartRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type PartRepository
func (_mock *PartRepository) List(ctx context.Context, partsUUID []uuid.UUID, partType model.PartType) ([]model.Part, error) {
	ret := _mock.Called(ctx, partsUUID, partType)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, model.PartType) ([]model.Part, error)); ok {
		return returnFunc(ctx, partsUUID, partType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, model.PartType) []model.Part); ok {
		r0 = returnFunc(ctx, partsUUID, partType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID, model.PartType) error); ok {
		r1 = returnFunc(ctx, partsUUID, partType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PartRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type PartRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - partsUUID []uuid.UUID
//   - partType model.PartType
func (_e *PartRepository_Expecter) List(ctx interface{}, partsUUID interface{}, partType interface{}) *PartRepository_List_Call {
	return &PartRepository_List_Call{Call: _e.mock.On("List", ctx, partsUUID, partType)}
}

func (_c *PartRepository_List_Call) Run(run func(ctx context.Context, partsUUID []uuid.UUID, partType model.PartType)) *PartRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 model.PartType
		if args[2] != nil {
			arg2 = args[2].(model.PartType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PartRepository_List_Call) Return(parts []model.Part, err error) *PartRepository_List_Call {
	_c.Call.Return(parts, err)
	return _c
}

func (_c *PartRepository_List_Call) RunAndReturn(run func(ctx context.Context, partsUUID []uuid.UUID, partType model.PartType) ([]model.Part, error)) *PartRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateReservedBatch provides a mock function for the type PartRepository
func (_mock *PartRepository) UpdateReservedBatch(ctx context.Context, parts []model.Part) error {
	ret := _mock.Called(ctx, parts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReservedBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []model.Part) error); ok {
		r0 = returnFunc(ctx, parts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PartRepository_UpdateReservedBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateReservedBatch'
type PartRepository_UpdateReservedBatch_Call struct {
	*mock.Call
}

// UpdateReservedBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - parts []model.Part
func (_e *PartRepository_Expecter) UpdateReservedBatch(ctx interface{}, parts interface{}) *PartRepository_UpdateReservedBatch_Call {
	return &PartRepository_UpdateReservedBatch_Call{Call: _e.mock.On("UpdateReservedBatch", ctx, parts)}
}

func (_c *PartRepository_UpdateReservedBatch_Call) Run(run func(ctx context.Context, parts []model.Part)) *PartRepository_UpdateReservedBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []model.Part
		if args[1] != nil {
			arg1 = args[1].([]model.Part)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PartRepository_UpdateReservedBatch_Call) Return(err error) *PartRepository_UpdateReservedBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PartRepository_UpdateReservedBatch_Call) RunAndReturn(run func(ctx context.Context, parts []model.Part) error) *PartRepository_UpdateReservedBatch_Call {
	_c.Call.Return(run)
	return _c
}
